import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { CheckCircle2, ChevronRight, X } from "lucide-react";
import "./style.css";

const getAsin=()=>document.querySelector<HTMLInputElement>("#ASIN")?.value ?? location.pathname.match(/\/dp\/([A-Z0-9]{10})/)?.[1] ?? "B0EASY001BR";
const mock={score:87,margin:18.4,roi:34.2,profit:13.76,sales:82,sellers:4,price:79.9,maxCost:42.3,quantity:8,days:18};

function Panel(){const [open,setOpen]=useState(true);const [saved,setSaved]=useState(false);if(!open)return <button className="es-fab" onClick={()=>setOpen(true)}>ES <span>87</span></button>;return <aside className="es-panel" aria-label="Análise Easy Seller"><header><div className="es-brand">easy<span>seller</span></div><button onClick={()=>setOpen(false)} aria-label="Fechar"><X size={18}/></button></header><div className="es-score"><div><small>OPORTUNIDADE</small><strong>{mock.score}<span>/100</span></strong></div><span className="es-good"><CheckCircle2 size={14}/> Muito boa</span></div><p className="es-copy">Boa margem, demanda consistente e concorrência moderada.</p><div className="es-grid"><Metric label="Preço" value={`R$ ${mock.price.toFixed(2)}`}/><Metric label="Lucro estimado" value={`R$ ${mock.profit.toFixed(2)}`}/><Metric label="Margem" value={`${mock.margin}%`}/><Metric label="ROI" value={`${mock.roi}%`}/><Metric label="Giro estimado" value={`~${mock.days} dias`}/><Metric label="Vendedores" value={`${mock.sellers}`}/></div><div className="es-callout"><small>VOCÊ PODE PAGAR ATÉ</small><strong>R$ {mock.maxCost.toFixed(2)}</strong></div><div className="es-test"><div><small>TESTE INICIAL SUGERIDO</small><strong>{mock.quantity} unidades</strong></div><span>R$ {(mock.quantity*38).toFixed(2)}</span></div><button className="es-primary" onClick={()=>{chrome.runtime.sendMessage({type:"SAVE_PRODUCT",payload:{asin:getAsin(),savedAt:new Date().toISOString()}});setSaved(true)}}>{saved?"Produto salvo":"Salvar produto"}<ChevronRight size={17}/></button><a href={`http://localhost:3000/?asin=${getAsin()}`} target="_blank" rel="noreferrer">Abrir análise completa</a><footer>Dados estimados • confiança média</footer></aside>}
function Metric({label,value}:{label:string;value:string}){return <div><small>{label}</small><strong>{value}</strong></div>}
const mount=document.createElement("div");mount.id="easy-seller-root";document.body.appendChild(mount);createRoot(mount).render(<Panel/>);
