import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {calculateFinancials,calculateOpportunityScore,calculateRecommendedQuantity} from '@easy-seller/calculations';
import {RefreshCw,X} from 'lucide-react';
import './style.css';

type Origin='REAL'|'ESTIMATED'|'INFERRED'; type Confidence='HIGH'|'MEDIUM'|'LOW';
type Signal<T>={value:T;origin:Origin;confidence:Confidence;source:string;observedAt:string};
type MonthlySalesPoint={month:string;estimatedUnits:number|null;latestRank:number|null;observations:number;observedAt:string|null;origin:'INFERRED';confidence:'LOW';source:'SALES_RANK_HEURISTIC_V1'};
type Intelligence={pricing:{price:Signal<number>;buyBoxPrice?:Signal<number|null>}|null;fees:{commission:Signal<number>;logistics:Signal<number>}|null;competition:{sellerCount:Signal<number>;amazonIsSeller:Signal<boolean>}|null;catalog:{title:Signal<string>;rating?:Signal<number>;reviewCount?:Signal<number>;historyAvailable:Signal<boolean>}|null;rank:{rank:Signal<number>;category:Signal<string>}|null;monthlySales:Signal<number>|null;monthlySalesHistory:MonthlySalesPoint[];turnoverDays:Signal<number>|null;changes:Array<{title:string;message:string;severity:string}>};
const match=location.pathname.match(/\/(?:dp|gp\/product)\/([A-Z0-9]{10})(?:[/?]|$)/i); const asin=match?.[1]?.toUpperCase();
const decimal=(value:string)=>{const clean=value.replace(/[^\d,.]/g,'');return Number(clean.includes(',')?clean.replace(/\./g,'').replace(',','.'):clean)||0};
const integer=(value:string)=>Number(value.replace(/\D/g,''))||0; const content=(selector:string)=>document.querySelector<HTMLElement>(selector)?.innerText.trim()??'';
const pagePrice=()=>decimal(content('#corePrice_feature_div .a-offscreen')||content('.a-price .a-offscreen')); const pageName=()=>content('#productTitle')||'Produto Amazon';
const pageRating=()=>decimal(content('#acrPopover .a-icon-alt')||content('[data-hook="rating-out-of-text"]')); const pageReviews=()=>integer(content('#acrCustomerReviewText'));
const pageSellerCount=()=>{const value=content('#buybox-see-all-buying-choices')||content('#olpLinkWidget_feature_div');const found=value.match(/(\d+)\s+(?:oferta|novo|vendedor)/i);return found?Number(found[1]):undefined};
const pageSalesRank=()=>{const value=['#productDetails_detailBullets_sections1','#detailBullets_feature_div','#productDetails_techSpec_section_1'].map(content).filter(Boolean).join('\n');const found=value.match(/(?:ranking|classifica[cç][aã]o)\s+dos\s+mais\s+vendidos[^#\d]*(?:n[ºo]\s*)?#?\s*([\d.\s]+)/i);if(!found)return {};const salesRank=integer(found[1]);const category=value.slice((found.index??0)+found[0].length).match(/\bem\s+([^\n(]+)/i)?.[1]?.trim();return salesRank>0?{salesRank,salesRankCategory:category||undefined}:{}};
const pageObservation=()=>{const merchant=`${content('#merchant-info')} ${content('#sellerProfileTriggerId')} ${content('#tabular-buybox-truncate-0')}`;return {title:pageName(),price:pagePrice()||undefined,buyBoxPrice:pagePrice()||undefined,rating:pageRating()||undefined,reviewCount:pageReviews()||undefined,sellerCount:pageSellerCount(),amazonIsSeller:merchant?/(amazon\.com\.br|vendido por amazon)/i.test(merchant):undefined,...pageSalesRank(),observedAt:new Date().toISOString()}};
const explanation=(signal?:Signal<unknown>|null)=>signal?`${signal.origin} · confiança ${signal.confidence} · fonte ${signal.source} · observado em ${new Date(signal.observedAt).toLocaleString('pt-BR')}`:'Dado indisponível — nenhuma fonte confiável retornou este campo.'; const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

function Panel(){
 const[open,setOpen]=useState(true),[salePrice,setSalePrice]=useState(pagePrice()),[cost,setCost]=useState(0),[shipping,setShipping]=useState(0),[packaging,setPackaging]=useState(0),[tax,setTax]=useState(4),[commission,setCommission]=useState(0),[logistics,setLogistics]=useState(0),[advertising,setAdvertising]=useState(0),[quantity,setQuantity]=useState(1),[intel,setIntel]=useState<Intelligence|null>(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{if(!asin)return;setLoading(true);setMessage('');try{const response=await fetch('http://localhost:3333/amazon/intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asin,page:pageObservation(),productCost:cost,inboundShipping:shipping,packaging,taxRate:tax/100,advertising,quantity})});if(!response.ok)throw new Error(`API ${response.status}`);const data=await response.json() as Intelligence;setIntel(data);if(data.pricing?.price.value)setSalePrice(data.pricing.price.value);if(data.fees){setCommission(data.fees.commission.value);setLogistics(data.fees.logistics.value)}}catch(error){setMessage(`Inteligência indisponível: ${error instanceof Error?error.message:'erro desconhecido'}. Os campos manuais continuam utilizáveis.`)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const sellerCount=intel?.competition?.sellerCount.value??0,monthlySales=intel?.monthlySales?.value??0,amazonIsSeller=intel?.competition?.amazonIsSeller.value??false;
 const financial=useMemo(()=>calculateFinancials({salePrice,productCost:cost,inboundShipping:shipping,packaging,taxRate:tax/100,amazonCommission:commission,amazonLogistics:logistics,advertising,quantity,targetMarginRate:.15}),[salePrice,cost,shipping,packaging,tax,commission,logistics,advertising,quantity]);
 const score=useMemo(()=>calculateOpportunityScore({monthlySales,netMarginPercent:financial.netMarginPercent,roiPercent:financial.roiPercent,priceStability:50,sellerCount,demandStability:intel?.rank?50:0,amazonIsSeller,inventoryRisk:intel?.rank?40:60}),[monthlySales,financial.netMarginPercent,financial.roiPercent,sellerCount,amazonIsSeller,intel?.rank]);
 const suggested=useMemo(()=>calculateRecommendedQuantity({monthlySalesEstimate:monthlySales,sellerCount,score:score.score,capitalAvailable:20000,unitCost:cost,riskLevel:intel?.rank?'MEDIUM':'HIGH',maxExposurePercent:5}),[monthlySales,sellerCount,score.score,cost,intel?.rank]);
 const save=async()=>{setSaving(true);setMessage('');try{const response=await fetch('http://localhost:3333/extension/analyses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asin,productName:intel?.catalog?.title.value??pageName(),salePrice,productCost:cost,inboundShipping:shipping,packaging,taxRate:tax/100,amazonCommission:commission,amazonLogistics:logistics,advertising,otherExpenses:0,quantity,monthlySales,sellerCount,priceStability:50,demandStability:intel?.rank?50:0,amazonIsSeller,inventoryRisk:intel?.rank?40:60,dataOrigin:'INFERRED'})});if(!response.ok)throw new Error(`API ${response.status}`);setMessage('Análise salva no Easy Seller.')}catch(error){setMessage(`Falha ao salvar: ${error instanceof Error?error.message:'erro desconhecido'}.`)}finally{setSaving(false)}};
 if(!open)return <button className="es-fab" onClick={()=>setOpen(true)}>ES <span>{score.score}</span></button>;
 const fields:[string,number,(value:number)=>void,Signal<unknown>|null|undefined][]=[['Preço de venda',salePrice,setSalePrice,intel?.pricing?.price],['Custo do produto',cost,setCost,null],['Frete de compra',shipping,setShipping,null],['Embalagem',packaging,setPackaging,null],['Imposto (%)',tax,setTax,null],['Comissão Amazon',commission,setCommission,intel?.fees?.commission],['Logística Amazon',logistics,setLogistics,intel?.fees?.logistics],['Publicidade',advertising,setAdvertising,null],['Quantidade',quantity,setQuantity,null]];
 const calculated:Signal<number>={value:0,origin:'INFERRED',confidence:intel?.rank?'MEDIUM':'LOW',source:'EASY_SELLER_CALCULATION_V1',observedAt:new Date().toISOString()};
 return <aside className="es-panel"><header><div className="es-brand">easy<span>seller</span></div><div><button onClick={()=>void load()} disabled={loading} title="Atualizar inteligência"><RefreshCw size={16}/></button><button onClick={()=>setOpen(false)} aria-label="Fechar"><X size={18}/></button></div></header><p className="es-asin">ASIN <strong>{asin}</strong></p>{loading&&<p className="es-loading">Consultando fontes disponíveis…</p>}<div className="es-score" title={explanation(calculated)}><div><small>SCORE · INFERRED</small><strong>{score.score}<span>/100</span></strong></div><b>{score.classification}</b></div><div className="es-signals"><Datum label="Buy Box" value={intel?.pricing?.buyBoxPrice?.value==null?'—':money(intel.pricing.buyBoxPrice.value)} signal={intel?.pricing?.buyBoxPrice}/><Datum label="Vendedores" value={intel?.competition?.sellerCount.value??'—'} signal={intel?.competition?.sellerCount}/><Datum label="Amazon vende" value={intel?.competition?amazonIsSeller?'Sim':'Não':'—'} signal={intel?.competition?.amazonIsSeller}/><Datum label="Sales Rank" value={intel?.rank?.rank.value??'—'} signal={intel?.rank?.rank}/><Datum label="Giro estimado" value={intel?.turnoverDays?`${intel.turnoverDays.value} dias`:'—'} signal={intel?.turnoverDays}/><Datum label="Reviews / rating" value={intel?.catalog?.reviewCount?`${intel.catalog.reviewCount.value} / ${intel.catalog.rating?.value??'—'}`:'—'} signal={intel?.catalog?.reviewCount}/></div><MonthlySalesChart points={intel?.monthlySalesHistory??[]}/><div className="es-fields">{fields.map(([label,value,setter,signal])=><label key={label} title={signal?explanation(signal):'Dado informado manualmente pelo usuário.'}>{label}{signal&&<Origin signal={signal}/>}<input type="number" min="0" step="0.01" value={value} onChange={event=>setter(Number(event.target.value))}/></label>)}</div><div className="es-grid"><Metric label="Preço" value={money(salePrice)} signal={intel?.pricing?.price}/><Metric label="Lucro/un." value={money(financial.netProfitPerUnit)} signal={calculated}/><Metric label="Margem" value={`${financial.netMarginPercent.toFixed(2)}%`} signal={calculated}/><Metric label="ROI" value={`${financial.roiPercent.toFixed(2)}%`} signal={calculated}/><Metric label="Preço máximo" value={money(financial.maxPurchasePrice)} signal={calculated}/><Metric label="Qtd. sugerida" value={String(suggested)} signal={calculated}/></div>{intel?.changes?.map(change=><p className={`es-alert ${change.severity.toLowerCase()}`} key={`${change.title}-${change.message}`}><strong>{change.title}</strong> {change.message}</p>)}<button className="es-primary" disabled={saving||salePrice<=0} onClick={()=>void save()}>{saving?'Salvando…':'Salvar análise'}</button>{message&&<p className="es-message">{message}</p>}<p className="es-legend">Passe o mouse nos selos para ver fonte, origem e confiança.</p><a href={`http://localhost:3000/?view=products&asin=${asin}`} target="_blank" rel="noreferrer">Abrir painel local</a></aside>
}
function MonthlySalesChart({points}:{points:MonthlySalesPoint[]}){const available=points.filter(point=>point.estimatedUnits!==null);const maximum=Math.max(...available.map(point=>point.estimatedUnits??0),1);const previous=points.at(-2)?.estimatedUnits??null,current=points.at(-1)?.estimatedUnits??null;const change=previous&&current!==null?Math.round((current-previous)/previous*100):null;const summary=change===null?'Histórico insuficiente para comparar':change===0?'Estável vs. mês anterior':`${change>0?'↑':'↓'} ${Math.abs(change)}% vs. mês anterior`;return <section className="es-sales-chart" title="Estimativa inferida do Sales Rank. Não representa vendas exatas."><div className="es-chart-header"><div><small>VENDAS ESTIMADAS · 3 MESES</small><strong>{summary}</strong></div><span>INFERRED · LOW</span></div><div className="es-bars">{points.map(point=><div className="es-bar-column" key={point.month}><div className={`es-bar ${point.estimatedUnits===null?'missing':''}`} style={{height:point.estimatedUnits===null?'5px':`${Math.max(16,(point.estimatedUnits/maximum)*62)}px`}} title={point.estimatedUnits===null?'Sem observação neste mês':`${point.estimatedUnits} un./mês estimadas · rank #${point.latestRank}`} /><strong>{point.estimatedUnits??'—'}</strong><small>{new Intl.DateTimeFormat('pt-BR',{month:'short',timeZone:'UTC'}).format(new Date(`${point.month}-01T12:00:00Z`)).replace('.','')}</small></div>)}</div><p>Estimativa por Sales Rank; meses sem observação permanecem vazios.</p></section>}
function Origin({signal}:{signal:Signal<unknown>}){return <span className={`es-origin ${signal.origin.toLowerCase()}`} title={explanation(signal)}>{signal.origin} · {signal.confidence}</span>}
function Datum({label,value,signal}:{label:string;value:React.ReactNode;signal?:Signal<unknown>|null}){return <div title={explanation(signal)}><small>{label}</small><strong>{value}</strong>{signal?<Origin signal={signal}/>:<span className="es-origin unavailable">INDISPONÍVEL</span>}</div>}
function Metric({label,value,signal}:{label:string;value:string;signal?:Signal<unknown>|null}){return <div title={explanation(signal)}><small>{label}</small><strong>{value}</strong>{signal&&<Origin signal={signal}/>}</div>}
if(asin){const mount=document.createElement('div');mount.id='easy-seller-root';document.body.appendChild(mount);createRoot(mount).render(<Panel/>)}
